# Generated by Django 3.2 on 2026-09-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='group',
            field=models.CharField(blank=True, help_text='রক্তের গ্রুপ', max_length=50, null=True, verbose_name='Blood Group'),
        ),
    ]
