# Generated by Django 3.2 on 2026-09-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('rewards', '0005_seed_streak_badges'),
        ('blogapp', '0004_alter_category_options'),
        ('accounts', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAdmin',
        ),
    ]
