# Generated by Django 3.2 on 2026-09-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('icon', models.CharField(default='award', help_text="Feather icon name, e.g. 'award' for feather-award.", max_length=50, verbose_name='Icon')),
                ('color', models.CharField(default='#cd7f32', max_length=20, verbose_name='Color')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('min_donations', models.PositiveIntegerField(unique=True, verbose_name='Minimum Approved Donations')),
            ],
            options={
                'ordering': ['min_donations'],
            },
        ),
    ]
