# Generated by Django 3.2 on 2026-09-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_seed_default_badges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['badge_type', 'min_donations', 'min_streak']},
        ),
        migrations.AddField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('tier', 'Tier (by total donations)'), ('streak', 'Streak (by consecutive donation cycles)')], default='tier', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='badge',
            name='min_streak',
            field=models.PositiveIntegerField(blank=True, help_text='Required for streak badges.', null=True, verbose_name='Minimum Streak'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='min_donations',
            field=models.PositiveIntegerField(blank=True, help_text='Required for tier badges.', null=True, verbose_name='Minimum Approved Donations'),
        ),
    ]
